# Generated by Django 5.1.4 on 2025-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='file',
            field=models.FileField(upload_to='uploaded_videos/'),
        ),
    ]
