# Generated by Django 5.1.4 on 2025-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0003_uploadedvideo_estimated_time_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideo',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='estimated_time_remaining',
        ),
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='processing_progress',
        ),
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
