# Generated by Django 5.1.4 on 2025-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0004_rename_uploaded_at_uploadedvideo_upload_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideo',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='status',
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='current_stage',
            field=models.CharField(default='Waiting to start', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
