# Generated by Django 5.1.4 on 2025-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0005_rename_upload_date_uploadedvideo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='current_stage',
            field=models.CharField(default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
