# Generated by Django 5.1.4 on 2025-01-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0006_remove_uploadedvideo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='file',
            field=models.FileField(upload_to='uploaded_videos/'),
        ),
    ]
