# Generated by Django 5.1.4 on 2025-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0007_alter_uploadedvideo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='current_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
